name: Simple Docker Build

# Trigger on a push to the 'main' branch (or 'production')
on:
  push:
    branches:
      - main  # Or 'production' if that's your branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to DockerHub (using secrets for username and password)
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and tag the Docker image
      - name: Build Docker image
        run: docker build -t sunilsuthar7/my-simple-app:latest .

      # Step 4: Push the image to DockerHub
      - name: Push Docker image
        run: docker push sunilsuthar7/my-simple-app:latest
